UI.Arcoline/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UI.Arcoline.Controllers
{
    public class DashboardController : BaseController
    {
        // GET: Dashboard
        public ActionResult Index()
        {
            return View();
        }
    }
}

UI.Arcoline/Controllers/NoticeController.cs
using Application.Arcoline;
using Data.Arcoline.Entidades;
using System;
using System.IO;
using System.Web;
using System.Web.Mvc;
using UI.Arcoline.Helper;

namespace UI.Arcoline.Controllers
{
    public class NoticeController : BaseController
    {
        private NoticeApp _notice = new NoticeApp();

        public ActionResult Index()
        {
            var response = _notice.GetNotices();
            return View(response.Objeto);
        }

        public ActionResult Details(Guid id)
        {
            var response = _notice.GetNotice(id);
            var notice = (Notice)response.Objeto;
            return View(notice);
        }

        public ActionResult Create()
        {
            ViewBag.Categories = new SelectList(_notice.CategoryCollection().ToArray(), "IdCategory", "Name");
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(Notice newObject, HttpPostedFileBase upload)
        {
            if (upload != null)
            {
                var extension = Path.GetExtension(upload.FileName);
                var cvName = "NOTICE" + DateTime.Now.ToString("yymmssfff") + extension;
                upload.SaveAs(HttpContext.Server.MapPath("~/Assets/Storage/NoticesIMG/") + cvName);
                newObject.Img = cvName;
            }

            var response = _notice.CreateNotice(newObject);
            var notice = (Notice)response.Objeto;
            var IdCategory = newObject.IdCategory;

            if (response.Exito)
            {
                TempData["Ok"] = response.Mensagem;
            }
            else
            {
                TempData["Erro"] = response.Mensagem;
            }

            if (IdCategory != null)
            {
                return RedirectToAction("Details", "Category", new { id = IdCategory });
            }
            else
            {
                TempData["Ok"] = "Noticia publicada com sucesso";
                return RedirectToAction("Details", new { id = notice.IdNotice });
            }
        }

        public ActionResult Edit(Guid id)
        {
            ViewBag.Categories = new SelectList(_notice.CategoryCollection().ToArray(), "IdCategory", "Name");
            var response = _notice.GetNotice(id);
            var notice = (Notice)response.Objeto;
            return View(notice);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(Guid id, Notice editObject, HttpPostedFileBase upload)
        {
            try
            {
                if (upload != null)
                {
                    var res = _notice.GetNotice(id);
                    var notice_before_updated = (Notice)res.Objeto;

                    var pathImg = HttpContext.Server.MapPath("~/Assets/Storage/NoticesIMG/") + notice_before_updated.Img;
                    ArcolineHelper.DeleteFile(pathImg);

                    var extension = Path.GetExtension(upload.FileName);
                    var cvName = "NOTICE" + DateTime.Now.ToString("yymmssfff") + extension;
                    upload.SaveAs(HttpContext.Server.MapPath("~/Assets/Storage/NoticesIMG/") + cvName);
                    editObject.Img = cvName;
                }

                ViewBag.Categories = new SelectList(_notice.CategoryCollection(), "IdCategory", "Name");
                var response = _notice.UpdateNotice(id, editObject);
                var notice = (Notice)response.Objeto;

                if (response.Exito)
                {
                    TempData["Ok"] = response.Mensagem;
                }
                else
                {
                    TempData["Erro"] = response.Mensagem;
                }
                return RedirectToAction("Details", "Category", new { id = notice.IdCategory });
            }
            catch
            {
                return View();
            }

        }

        public ActionResult Delete(Guid id)
        {
            try
            {
                var res = _notice.GetNotice(id);
                var notice = (Notice)res.Objeto;
                var IdCategory = notice.IdCategory;
                var response = _notice.DeleteNotice(id);

                var pathImg = HttpContext.Server.MapPath("~/Assets/Storage/NoticesIMG/") + notice.Img;
                ArcolineHelper.DeleteFile(pathImg);

                if (response.Exito)
                {
                    TempData["Ok"] = response.Mensagem;
                }
                else
                {
                    TempData["Erro"] = response.Mensagem;
                }
                return RedirectToAction("Details", "Category", new { id = IdCategory });
            }
            catch
            {
                return View();
            }
        }

    }
}

UI.Arcoline/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title ::. Arcoline</title>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400italic,600,700%7COpen+Sans:300,400,400italic,600,700">
    <link href="~/Assets/css/oneui.min.css" rel="stylesheet" />
    <link rel="icon" type="image/png" href="~/favicon.png" />
    <link href="~/Assets/css/application.css" rel="stylesheet" />


</head>

<body>
    <div id="page-container" class="sidebar-o sidebar-dark enable-page-overlay side-scroll page-header-fixed">
        <nav id="sidebar" aria-label="Main Navigation">
            <div class="content-header bg-white-5" style="padding: 60px 15px;">
                <a class="font-w600 text-dual" href="@Url.Action("Index","Dashboard")">
                    <img class="img-fluid" src="~/Assets/img/logotipo.png" style="height: 50px!important;" />
                </a>
            </div>
            @Html.Partial("_SideNavigation")
        </nav>

        <header id="page-header">
            <button type="button" class="btn btn-sm btn-dual mr-2 d-none d-lg-inline-block" data-toggle="layout" data-action="sidebar_mini_toggle" style="position: absolute; margin: 15px 1.875rem;">
                <i class="fa fa-fw fa-ellipsis-v"></i>
            </button>
        </header>

        <main id="main-container">
            <div class="">
                @RenderBody()
            </div>
        </main>

    </div>

    <script src="~/Assets/js/oneui.core.min.js"></script>
    <script src="~/Assets/js/oneui.app.min.js"></script>

    <script src="~/Assets/js/notify/UI.v4.min.js"></script>
    <script src="~/Assets/js/jquery.simpleTableSort.js"></script>
    <script src="~/Assets/js/Application.js"></script>

    <link href="~/Assets/summernote/summernote.min.css" rel="stylesheet" />
    <script src="~/Assets/summernote/summernote.min.js"></script>

    <!-- ================================================================== -->

    @if (TempData["Erro"] != null)
    {
        <script>
            MsgErro('@(TempData["Erro"].ToString())');
        </script>
    }

    @if (TempData["Ok"] != null)
    {
        <script>
            MsgOk('@(TempData["Ok"].ToString())');
        </script>
    }

    @if (TempData["Alert"] != null)
    {
        <script>
            MsgAlert('@(TempData["Alert"].ToString())');
        </script>
    }

    @if (TempData["Info"] != null)
    {
        <script>
            MsgInfo('@(TempData["Info"].ToString())');
        </script>
    }

    <!-- ================================================================== -->

</body>
</html>

<script>

    $(document).ready(function() {
      $('.summernote').summernote();
    });

</script>

UI.Arcoline/Views/Shared/_LayoutAccount.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>@ViewBag.Title ::. Arcoline</title>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400italic,600,700%7COpen+Sans:300,400,400italic,600,700">
    <link href="~/Assets/css/oneui.min.css" rel="stylesheet" />
    <link rel="icon" type="image/png" href="~/favicon.png" />
    <link href="~/Assets/css/application.css" rel="stylesheet" />
</head>
<body>

    <div id="page-container">
        <main id="main-container">

            <div class="hero-static d-flex align-items-center">
                <div class="w-100">
                    <div class="content content-full bg-white">
                        <div class="row justify-content-center">
                            <div class="col-sm-12 col-md-6 col-lg-3 py-4">
                                <!-- Header -->
                                <div class="text-center">
                                    <img src="~/Assets/img/logotipo.png" style="width: 200px;" />
                                </div>
                                <br />
                                <br />
                                @RenderBody()
                            </div>
                        </div>
                    </div>
                    <div class="font-size-sm text-center text-muted py-3">
                    </div>
                </div>
            </div>
        </main>
    </div>

    <script src="~/Assets/js/oneui.core.min.js"></script>
    <script src="~/Assets/js/oneui.app.min.js"></script>
</body>
</html>

UI.Arcoline/Views/Shared/_LayoutSite.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title ::. Arcoline</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="~/favicon.png" />
    <link href="~/Assets/css/site.css" rel="stylesheet" />
</head>

<body>

    <div class="">
        @RenderBody()
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

UI.Arcoline/Views/Shared/_SideNavigation.cshtml
<div class="content-side content-side-full">
    <ul class="nav-main">
        <li class="nav-main-item">
            <a class="nav-main-link" href="@Url.Action("Index","Dashboard")">
                <i class="nav-main-link-icon si si-home"></i>
                <span class="nav-main-link-name">Inicio</span>
            </a>
        </li>

        <li class="nav-main-item">
            <a class="nav-main-link" href="@Url.Action("Index","Category")">
                <i class="nav-main-link-icon si si-layers"></i>
                <span class="nav-main-link-name">Categorias</span>
            </a>
        </li>

        <li class="nav-main-item">
            <a class="nav-main-link" href="@Url.Action("Index","Notice")">
                <i class="nav-main-link-icon si si-badge"></i>
                <span class="nav-main-link-name">Noticias</span>
            </a>
        </li>



        <li class="divider"></li>

        <li class="nav-main-item">
            <a class="nav-main-link" href="@Url.Action("LogOff", "Account")">
                <i class="nav-main-link-icon si si-logout"></i>
                <span class="nav-main-link-name">Sair</span>
            </a>
        </li>

    </ul>
</div>